package com.marsapps.triptip.main

class Constants {

    companion object {
        object Extras {
            const val COUNTRY_EXTRA = "Country"
            const val COUNTRY_NOTIFICATION_EXTRA = "CountryNotification"
        }

        object Data {
            const val COUNTRY_NAME_DATA = "CountryName"
            const val NOTIFICATION_ID_DATA = "NotificationID"
        }

        object Notifications {
            const val ID = "tipNotification"
            const val NAME = "Tip Notification"
        }

        object Bundles {
            const val ADDED_TO_TRAVEL_LIST = 1
        }

        object Preferences {
            const val TRAVEL_LIST_CHANGED = "travelListChanged"
        }

        object Ignore {
            val DISABLE_COUNTRIES_HIGHLIGHT = listOf("Israel")
        }

        object RecommendedMonths {

            enum class Months(val monthNumber: Int, val monthName: String) {
                JANUARY(1, "January"),
                FEBRUARY(2, "February"),
                MARCH(3, "March"),
                APRIL(4, "April"),
                MAY(5, "May"),
                JUNE(6, "June"),
                JULY(7, "July"),
                AUGUST(8, "August"),
                SEPTEMBER(9, "September"),
                OCTOBER(10, "October"),
                NOVEMBER(11, "November"),
                DECEMBER(12, "December")
            }

            val MONTHS = hashMapOf("af" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.SEPTEMBER, Months.OCTOBER),
                "ax" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "al" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "dz" to listOf(Months.MARCH, Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "as" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "ad" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "ao" to listOf(Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "ai" to listOf(Months.APRIL, Months.MAY),
                "aq" to listOf(Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "ag" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY),
                "ar" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.APRIL, Months.MAY, Months.JUNE),
                "am" to listOf(Months.JUNE, Months.OCTOBER),
                "aw" to listOf(Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST),
                "au" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "at" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "az" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.SEPTEMBER, Months.OCTOBER),
                "bs" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "bh" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MARCH),
                "bd" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "bb" to listOf(Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "by" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "be" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "bz" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "bj" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY),
                "bm" to listOf(Months.MARCH, Months.APRIL, Months.MAY),
                "bt" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.APRIL),
                "bo" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "bq" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "ba" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "bw" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "bv" to listOf(),
                "br" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "io" to listOf(Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "um" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "vg" to listOf(Months.MARCH, Months.APRIL, Months.JULY, Months.AUGUST),
                "vi" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "bn" to listOf(Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY),
                "bg" to listOf(Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER, Months.JUNE, Months.AUGUST),
                "bf" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY),
                "bi" to listOf(Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "kh" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "cm" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY),
                "ca" to listOf(Months.MAY, Months.JUNE),
                "cv" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY, Months.JUNE),
                "ky" to listOf(Months.MARCH, Months.APRIL, Months.MAY, Months.JUNE),
                "cf" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY),
                "td" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "cl" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "cn" to listOf(Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER, Months.JUNE, Months.AUGUST),
                "cx" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "cc" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "co" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "km" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "cg" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER),
                "cd" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER),
                "ck" to listOf(Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER),
                "cr" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "hr" to listOf(Months.MAY, Months.JUNE, Months.SEPTEMBER, Months.OCTOBER),
                "cu" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY),
                "cw" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "cy" to listOf(Months.MARCH, Months.APRIL, Months.MAY),
                "cz" to listOf(Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER, Months.JUNE, Months.AUGUST),
                "dk" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST),
                "dj" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY),
                "dm" to listOf(Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY),
                "do" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST),
                "ec" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY),
                "eg" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "sv" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "gq" to listOf(Months.JULY, Months.AUGUST),
                "er" to listOf(Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER),
                "ee" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "et" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY, Months.JUNE),
                "fk" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "fo" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "fj" to listOf(Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "fi" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST),
                "fr" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "gf" to listOf(Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "pf" to listOf(Months.JUNE, Months.JULY, Months.AUGUST),
                "tf" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "ga" to listOf(Months.JUNE, Months.JULY, Months.AUGUST),
                "gm" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY, Months.JUNE),
                "ge" to listOf(Months.MAY, Months.JUNE, Months.SEPTEMBER),
                "de" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "gh" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "gi" to listOf(Months.AUGUST, Months.SEPTEMBER),
                "gr" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "gl" to listOf(Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "gd" to listOf(Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY),
                "gp" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY),
                "gu" to listOf(Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "gt" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "gg" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "gn" to listOf(Months.NOVEMBER, Months.DECEMBER),
                "gw" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "gy" to listOf(Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "ht" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "hm" to listOf(),
                "va" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "hn" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "hk" to listOf(Months.OCTOBER, Months.NOVEMBER),
                "hu" to listOf(Months.MARCH, Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "is" to listOf(Months.JUNE, Months.JULY, Months.AUGUST),
                "in" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "id" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "ci" to listOf(Months.NOVEMBER, Months.JANUARY, Months.FEBRUARY),
                "ir" to listOf(Months.MARCH, Months.APRIL, Months.MAY, Months.OCTOBER),
                "iq" to listOf(Months.JUNE, Months.JULY, Months.AUGUST),
                "ie" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.SEPTEMBER, Months.OCTOBER),
                "im" to listOf(Months.SEPTEMBER, Months.OCTOBER),
                "il" to listOf(Months.APRIL, Months.MAY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "it" to listOf(Months.APRIL, Months.JUNE, Months.SEPTEMBER, Months.OCTOBER),
                "jm" to listOf(Months.NOVEMBER, Months.DECEMBER),
                "jp" to listOf(Months.MARCH, Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "je" to listOf(Months.MAY, Months.OCTOBER, Months.JULY, Months.AUGUST, Months.JUNE, Months.SEPTEMBER),
                "jo" to listOf(Months.MARCH, Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "kz" to listOf(Months.JULY, Months.AUGUST, Months.APRIL, Months.JUNE, Months.SEPTEMBER, Months.OCTOBER),
                "ke" to listOf(Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "ki" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "kw" to listOf(Months.MARCH, Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER),
                "kg" to listOf(Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "la" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "lv" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "lb" to listOf(Months.APRIL, Months.MAY, Months.JUNE),
                "ls" to listOf(Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "lr" to listOf(Months.DECEMBER, Months.JULY, Months.MAY, Months.JUNE, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "ly" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST),
                "li" to listOf(),
                "lt" to listOf(Months.JUNE, Months.AUGUST),
                "lu" to listOf(Months.MAY, Months.JUNE, Months.SEPTEMBER),
                "mo" to listOf(Months.OCTOBER, Months.DECEMBER),
                "mk" to listOf(Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "mg" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "mw" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "my" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY),
                "mv" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "ml" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY),
                "mt" to listOf(Months.MARCH, Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "mh" to listOf(Months.NOVEMBER, Months.JUNE, Months.MARCH),
                "mq" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "mr" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "mu" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER, Months.DECEMBER),
                "yt" to listOf(Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "mx" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "fm" to listOf(Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.OCTOBER),
                "md" to listOf(Months.MAY, Months.JUNE, Months.AUGUST, Months.OCTOBER),
                "mc" to listOf(Months.APRIL, Months.OCTOBER),
                "mn" to listOf(Months.JULY, Months.AUGUST),
                "me" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.SEPTEMBER, Months.OCTOBER, Months.JULY, Months.AUGUST),
                "ms" to listOf(Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY),
                "ma" to listOf(Months.MARCH, Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER),
                "mz" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "mm" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY),
                "na" to listOf(Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "nr" to listOf(Months.MARCH, Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "np" to listOf(Months.OCTOBER, Months.NOVEMBER),
                "nl" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "nc" to listOf(Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "nz" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY),
                "ni" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "ne" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY),
                "ng" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.JANUARY),
                "nu" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "nf" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "kp" to listOf(Months.MARCH, Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER),
                "mp" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY, Months.JUNE),
                "no" to listOf(Months.JUNE, Months.JULY, Months.AUGUST),
                "om" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "pk" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "pw" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "ps" to listOf(Months.MARCH, Months.APRIL, Months.MAY),
                "pa" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "pg" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "py" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "pe" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "ph" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "pn" to listOf(Months.FEBRUARY, Months.MARCH, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "pl" to listOf(Months.MARCH, Months.MAY, Months.JUNE, Months.SEPTEMBER, Months.OCTOBER),
                "pt" to listOf(Months.MARCH, Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER),
                "pr" to listOf(Months.APRIL, Months.MAY, Months.JUNE),
                "qa" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "xk" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "re" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "ro" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "ru" to listOf(Months.MAY, Months.JUNE),
                "rw" to listOf(Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "bl" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "sh" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "kn" to listOf(Months.MAY, Months.JUNE, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "lc" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "mf" to listOf(Months.MAY, Months.JUNE, Months.NOVEMBER, Months.DECEMBER),
                "pm" to listOf(Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "vc" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "ws" to listOf(Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "sm" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.SEPTEMBER, Months.OCTOBER),
                "st" to listOf(Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "sa" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY),
                "sn" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY),
                "rs" to listOf(Months.JUNE, Months.JULY, Months.AUGUST),
                "sc" to listOf(Months.APRIL, Months.MAY, Months.OCTOBER),
                "sl" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY),
                "sg" to listOf(Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "sx" to listOf(Months.MAY, Months.JUNE, Months.NOVEMBER, Months.DECEMBER),
                "sk" to listOf(Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER),
                "si" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "sb" to listOf(Months.JUNE, Months.JULY),
                "so" to listOf(Months.JANUARY, Months.FEBRUARY),
                "za" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY),
                "gs" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "kr" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "ss" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY),
                "es" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "lk" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "sd" to listOf(Months.DECEMBER, Months.JANUARY, Months.FEBRUARY),
                "sr" to listOf(Months.FEBRUARY, Months.MARCH, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "sj" to listOf(Months.JUNE),
                "sz" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "se" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "ch" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.SEPTEMBER, Months.OCTOBER),
                "sy" to listOf(Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER),
                "tw" to listOf(Months.MARCH, Months.APRIL, Months.MAY),
                "tj" to listOf(Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "tz" to listOf(Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "th" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "tl" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY),
                "tg" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY),
                "tk" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER),
                "to" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "tt" to listOf(Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.MAY),
                "tn" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.SEPTEMBER, Months.OCTOBER),
                "tr" to listOf(Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER),
                "tm" to listOf(Months.MARCH, Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER, Months.NOVEMBER, Months.JULY, Months.AUGUST),
                "tc" to listOf(Months.APRIL, Months.MAY),
                "tv" to listOf(Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "ug" to listOf(Months.JUNE, Months.JULY, Months.AUGUST, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY),
                "ua" to listOf(Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "ae" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "gb" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.DECEMBER),
                "us" to listOf(),
                "uy" to listOf(Months.OCTOBER, Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH),
                "uz" to listOf(Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER),
                "vu" to listOf(Months.APRIL, Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "ve" to listOf(Months.NOVEMBER, Months.DECEMBER, Months.JANUARY, Months.FEBRUARY, Months.MARCH, Months.APRIL),
                "vn" to listOf(Months.FEBRUARY, Months.MARCH, Months.APRIL, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "wf" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER),
                "eh" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST, Months.SEPTEMBER, Months.OCTOBER),
                "ye" to listOf(Months.APRIL, Months.MAY, Months.SEPTEMBER, Months.OCTOBER),
                "zm" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST),
                "zw" to listOf(Months.MAY, Months.JUNE, Months.JULY, Months.AUGUST))
         }
    }

    object REST {
        const val SELF_URL = "."
        const val BASE_GOOGLE_API_URL = "https://maps.googleapis.com/maps/api/place/"
        private const val BASE_URL = "https://restcountries.eu"
        const val BASE_FLAGS_URL = "https://www.countryflags.io/"
        const val BASE_API_URL = "$BASE_URL/rest/v2/"
        const val PLACES_URL = "findplacefromtext/json?inputtype=textquery&fields=photos"
        const val IMAGES_URL = "${BASE_GOOGLE_API_URL}photo?&maxwidth=1200&photoreference="
    }
}